osx_image: xcode9.2
dist: trusty
sudo: false
language: node_js
node_js:
- node
os:
- osx
env:
  global:
  - ELECTRON_CACHE=$HOME/Library/Caches/electron
  - ELECTRON_BUILDER_CACHE=$HOME/Library/Caches/electron-builder
  - SYNC_STORJ_VERSION=0.0.23
  - SYNC_SIA_VERSION=0.1.3
  - secure: D/44TBDwD0YEOmHcnKu5qPwcVnksQwLb9D3s2ww/2KS55k0ueO7oawtoGLc7Ogs3HhthAZYwonLLC6beqqWoqSi3VuhBwEtVis6leM27ib2Agb9x+BCbh/Br1vFZI4TFLNSGqdbyswIvg7iVODGuj2HGwStY46ZMhsOyu3i50KH0vewoPNG4JT/Qf6EUKce9/BHRIwaTSriXHfz1VBdznvu24vpfVqxDbJNfh6i1TYkGT8NmEkVRR0iMQFBidQQ9dX7jhy0OSR6kt6dV9z6jvRkcyQrVRqZqc4HdPQWmzqjzNM8nHs8aDoDtqoIbr8h1Lm1tcdkcIPxDQ40Zd2JgN0TpGRb/o5o6cCGXhCT+zTWeq2HtBjPbgT8pQ13feCtB5QNJF8qdT92VqBbs5YXvF+vpK9qx72Wf0+mJasr1inN5VM1Eid4ou3mDPhriQMC9Z1Hg05GWChEwCJPJk+m+DKzKrgLde1gmXY3APQRVtDsfIEmBSv7o2EDoy1/GTJ+sJUXa/Y3fuhR7T0TtFZBhUU5OE0RYLR3AAB8d361wh22QUtGBiXBvisT3Llj8LfUrxHarEBj0rXH57WGOg5spxhcdH6AbgkMNWLJPn++kNs8gyuzj8ZthvaLmSMb0DcsQLq7Zc/93FChda5DidOtTj8DQ4T4qhXpzO4v3dikMyEk=
cache:
  directories:
  - node_modules
  - "$HOME/Library/Caches/electron"
  - "$HOME/Library/Caches/electron-builder"
  - "$HOME/.npm/_prebuilds"
script:
- npm run test:coverage
- npm run build
before_cache:
- rm -rf $HOME/Library/Caches/electron-builder/wine
after_success:
- npm run coveralls
- brew upgrade python
- pip install slack-cli
- '[ "$TRAVIS_PULL_REQUEST" != "false" ] && npm run dist && slack-cli -d dev -f dist/Goobox-0.1.4-setup_x64.exe && slack-cli -d dev -f dist/Goobox-0.1.4.dmg'
before_deploy:
- NODE_ENV=production npm run build
- npm run dist
deploy:
  provider: releases
  api_key:
    secure: NW1GGTAdJQpjlWnRvIXVNWm7bsEb33l+inZu4HpG7oKse73YSE6pr8/p0aDO2DHhq1YpTh8eQ2ulGBk3dhFWNS39dlTEdhN7tRLnZlBmxJe2fwlMVBkeLDlPWFWDVPHP/dZ8IAfaOZ98ehphlM8FYjqkRaVse+dFyOGqC3qfVgaj/4RnJns/wmQtnOapKgMd89GYghnhPsaVec2kT9zO7uu80GpzXG1lIVW0mwFBqdKBlqKynm7K4VdRaze0mwFvLnJWdHc8XRwYZoWUxGsUzuJBw1Hie8FzDTLdTs3SbDJJ4IIRHcU0eYdN+CLWBXfCsgJOReifgWbIHQ48AEn5E5zNN9UbRuUf8ghGtArS6KPymnKAyzj6gT0If3QAeVQtjeRrWhzt8naL9GjrgWv2kLkwDKZNiuoip8eKkfJktBs1vsZi6RUa89lgp9Eb/fWbG0g6KpAn6fZcyZDlch0j5RUUAogc3OItBpilu9PK1CyKs25HhDKpUYuDEWauFQAZeulf+puMUfk+OGQI7I0+hlxN0KdK3A2oixevNn+l6UFil3vPoxBIo89TmLEYLXdQ3PvI7XqpEfpsIP9SOq4psOuOqZ24JqhDo9NIlgFOQjFCX0ul9M4ToGvKMT2OiJQR01W19NceJd/ZTVM1mRlzGtaMPVehKrU9+G14bJ6c9XU=
  skip_cleanup: true
  file:
  - dist/Goobox-0.1.4-setup_x64.exe
  on:
    tags: true
    repo: GooBox/goobox-community-gui
