osx_image: xcode10.1
dist: trusty
sudo: false
language: node_js
node_js:
- node
os:
- osx
env:
  global:
  - ELECTRON_CACHE=$HOME/Library/Caches/electron
  - ELECTRON_BUILDER_CACHE=$HOME/Library/Caches/electron-builder
  - secure: tkInSF4UT6PO8SydezSNcaMYhGygtN9q/pTV+jprrGeJ1LAZJrhuytwdlopCl9/BAcOBDATOh02PX5Oa8pZAl84ARhOTLbKYdGycXtW65PGXsGzx4ORJ4fVAp2N684NNNPFxVqHrkG6DKjKhDoeHILysVJN2ZTfzYI6wCaFsW9Jzelc5xzz3/ELzUM9TjUTLW5rlIW9awtkonlKA3LBiWDZBPke7ch9VrhDyV9V8EStJPFnq6lqSLz1sNzf1bbz8x3cYVH5YhKhkbutugTMedsWJ+kp1HAVn0Gz52Wg11D32d91ym9HuvQuQoTbIge+HLj5uky6+CbNp0GIK0adOZdBAXITLrk1TilNHEz74XwLWWfYcLGV06qFgzXhHIxDR/qx5SNsBLLVefdbpw1JzGmp0cIre9ahUbfm4GrmZODW2JzHHBd8w+QEzxrpYZaFeXoqN3qvX7mmK3tN1sI1Ylm8A16AjpECoDZoFQb6ikVdV9McjtlJ6QwFZUqg0IKQIxB+OEnQ8dl1vFP37jjx1nNLh9qYmUCw7Gug0o2CQ7hFgmgqCh1ik36e6GfDowhgRdsPkCI8yKB/hBT8f6z2kuVFQQ7f3Dz3vHCeKntEtdNnUR1AwqrMIWr8dye/wSbgsLtCKlQPXDQkWUrFKvHWvo7bguWYIClvyEVr+D1XmLvQ=
  - secure: YDVnLB8k2qKl6HkJD4mIHkjDpQXTYCRk0zg+0g4IZo3ZOcFoLdTIxIyfXCpT2H8FnMt1Rk+90uU85Ib3QZEkACLx8+PM6cTWnrRubbhWzbhbJdnOmqZ11cnxaiyRmw7lQqlGZxqDoRnePX3xIG8gpiwVcoJMTEg13PAkkq4k/YfFbyTB7Rll+OsQc4bqFC/K0IQSQJMznw4wAx4/2s4RWWyArKZZPGYG6AM+qkKAJg9h+zrpei9lDoF6mNmlbCH6DtsgpqwRGZoIR+ll5nXn2BkjVw3PP751dAn1aXx8+i/lKL0CYgKCIjMAKk5px2n81RXr448xPH0+BOlKx2nqPXbBJLfjpf+WGXWDkn50bjcpuuedmFBqof4J1o0xey+Dr7tXPlOXpU+BomASJuJeGyRfvwh5AuZTi7b766fcm6UVjl54NAUdyspKgC3GS1QbcZyO89dMOdenXHhzo60W5XOBqy/vJdpRnSvC5giMCWkrwcpaezYWImyIKdrn9PD3/HFVBhx7iOj+1fiQ8WU6CUu/YxZa7SOPOv2A3q64IGrwijtHORmkjiCKZg8jpzMqOAuI9rEqieomj1lGswZTloDMpYqo5DIjxtqnDDzkfRtPuHgveGOpbO0dsgjw+g7Bi7R2FAj+O0FXCPQFJvD2BSeK0sS8kvcklVq+0AcURdo=
cache:
  directories:
  - node_modules
  - "$HOME/Library/Caches/electron"
  - "$HOME/Library/Caches/electron-builder"
  - "$HOME/.npm/_prebuilds"
script:
- yarn test:coverage
- yarn run check
- "./ci-build.sh"
before_cache:
- rm -rf $HOME/Library/Caches/electron-builder/wine
after_success:
- yarn coveralls
