environment:
  nodejs_version: Current
install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - yarn --version
  - yarn install
test_script:
  - yarn test
  - yarn run check
build: off
